trigger:
- main

pool:
  vmImage: 'windows-latest'
variables:
- name: 'devopsAccount' 
  value: 'projectName'
- name: 'projectName' # new variable defined in YAML
  value: 'contosoads'

stages:
- stage: Example
  jobs:
  - job: DisplayValues
    steps:
    - script: |
        echo "Inner Variable 1:"  coalesce(variables.projectName,'')
        echo "Inner Variable 2:"  coalesce(variables.$(devopsAccount),'')
      displayName: 'Display Variable Values'
