trigger:
- main

pool:
  vmImage: 'windows-latest'
variables:
- name: 'serviceConnectionClientIdSecretName' 
  value: 'kvVar'
- name: 'localVar' # new variable defined in YAML
  value: $(serviceConnectionClientIdSecretName)'
- name: kvVar
  value: 'final'

stages:
- stage: Example
  jobs:
  - job: DisplayValues
    steps:
    - task: CmdLine@2
      inputs:
        script: 'az bicep version'
